# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20170409_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('0', 'radio button'), ('1', 'select'), ('2', 'checkbox'), ('3', 'multiselect')], default=0, max_length=1),
            preserve_default=False,
        ),
    ]
