# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 00:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_choice_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='poll.Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='poll.Poll'),
            preserve_default=False,
        ),
    ]
