# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20170414_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('0', 'radio'), ('1', 'select'), ('2', 'checkbox'), ('3', 'multiple')], max_length=1),
        ),
    ]
