# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0009_auto_20170416_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', 'radio'), ('select', 'select'), ('checkbox', 'checkbox'), ('multiple', 'multiple')], max_length=1),
        ),
    ]
